version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - ls -lah
      - rm *.yml
      - rm requirements.txt
      - rm LICENSE
      - rm README.md
      - rm -rf cf
artifacts:
  files:
    - "**/*"
  name: $(date +%Y-%m-%d)
